# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UAV.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UAV_CONTROLS(object):
    def setupUi(self, UAV_CONTROLS):
        self.progressStatus = 0

        UAV_CONTROLS.setObjectName("UAV_CONTROLS")
        UAV_CONTROLS.resize(1051, 546)
        UAV_CONTROLS.setStyleSheet("background-color:rgb(241, 239, 202)\n"
"")
        self.centralwidget = QtWidgets.QWidget(UAV_CONTROLS)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(50, 20, 631, 501))
        self.graphicsView.setStyleSheet("border-color: rgb(239, 41, 41);\n"
"background-color: rgb(186, 189, 182);\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: black;")
        self.graphicsView.setObjectName("graphicsView")
        self.manualRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.manualRadio.setGeometry(QtCore.QRect(750, 20, 181, 31))
        self.manualRadio.setStyleSheet("QRadioButton::indicator { width: 30px; height: 30px;};\n"
"font: italic 22pt \"Ubuntu\";\n"
"")
        self.manualRadio.setObjectName("manualRadio")
        self.gestureRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.gestureRadio.setGeometry(QtCore.QRect(750, 120, 181, 31))
        self.gestureRadio.setStyleSheet("QRadioButton::indicator { width: 30px; height: 30px;};")
        self.gestureRadio.setObjectName("gestureRadio")
        self.EmergencyStopButton = QtWidgets.QPushButton(self.centralwidget)
        self.EmergencyStopButton.setGeometry(QtCore.QRect(760, 400, 221, 111))
        self.EmergencyStopButton.setStyleSheet("background-color: rgb(204, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Ubuntu\";")
        self.EmergencyStopButton.setObjectName("EmergencyStopButton")



        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(760, 360, 221, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.ShutDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShutDownButton.setGeometry(QtCore.QRect(880, 270, 141, 81))
        self.ShutDownButton.setStyleSheet("\n"
"border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Ubuntu\";\n"
"background-color: rgb(255, 106, 6);")
        self.ShutDownButton.setObjectName("ShutDownButton")
        self.StartupButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartupButton.setGeometry(QtCore.QRect(730, 270, 141, 81))
        self.StartupButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Ubuntu\";\n"
"background-color: rgb(121, 255, 97);")
        self.StartupButton.setObjectName("StartupButton")
        self.FollowRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.FollowRadio.setGeometry(QtCore.QRect(750, 70, 181, 31))
        self.FollowRadio.setStyleSheet("QRadioButton::indicator { width: 30px; height: 30px;};\n"
"font: italic 22pt \"Ubuntu\";\n"
"")
        self.FollowRadio.setObjectName("FollowRadio")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(730, 160, 291, 91))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        UAV_CONTROLS.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(UAV_CONTROLS)
        self.statusBar.setObjectName("statusBar")
        UAV_CONTROLS.setStatusBar(self.statusBar)

        self.retranslateUi(UAV_CONTROLS)

        self.EmergencyStopButton.clicked.connect(self.changeProgressBar)

        QtCore.QMetaObject.connectSlotsByName(UAV_CONTROLS)

    def changeProgressBar(self):
        self.statusBar = 100
        self.progressBar.setProperty("value", self.statusBar)

    def retranslateUi(self, UAV_CONTROLS):
        _translate = QtCore.QCoreApplication.translate
        UAV_CONTROLS.setWindowTitle(_translate("UAV_CONTROLS", "MainWindow"))
        self.manualRadio.setText(_translate("UAV_CONTROLS", "Manual Override"))
        self.gestureRadio.setText(_translate("UAV_CONTROLS", "Gesture Control"))
        self.EmergencyStopButton.setText(_translate("UAV_CONTROLS", "Emergency Stop"))
        self.ShutDownButton.setText(_translate("UAV_CONTROLS", "Shutdown"))
        self.StartupButton.setText(_translate("UAV_CONTROLS", "Startup"))
        self.FollowRadio.setText(_translate("UAV_CONTROLS", "Follow Mode"))
        self.textBrowser.setHtml(_translate("UAV_CONTROLS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello World</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UAV_CONTROLS = QtWidgets.QMainWindow()
    ui = Ui_UAV_CONTROLS()
    ui.setupUi(UAV_CONTROLS)
    UAV_CONTROLS.show()
    sys.exit(app.exec_())
